<?php
require_once __DIR__ . '/../../../core/libs/fpdf/fpdf.php';
require_once __DIR__ . '/../../models/Equipment.php';

class EquipmentReportController {

    /**
     * Generate PDF report for equipment inventory
     */
    public function generatePDF() {
        // Get equipment data
        $model = new Equipment();
        $data = $model->getInventoryReport();
        
        // Create PDF
        $pdf = new FPDF('P', 'mm', 'A4');
        $pdf->AddPage();
        $pdf->SetAutoPageBreak(true, 15);
        
        // Header
        $pdf->SetFont('Arial', 'B', 18);
        $pdf->SetTextColor(75, 0, 130); // Theme purple
        $pdf->Cell(0, 12, 'Equipment Inventory Report', 0, 1, 'C');
        
        $pdf->SetFont('Arial', '', 10);
        $pdf->SetTextColor(100, 100, 100);
        $pdf->Cell(0, 6, 'University of Colombo - Sports E-Portal', 0, 1, 'C');
        $pdf->Cell(0, 6, 'Generated: ' . date('F j, Y - g:i A'), 0, 1, 'C');
        $pdf->Ln(8);
        
        // Summary Section
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->SetTextColor(0, 0, 0);
        $pdf->Cell(0, 8, 'Summary', 0, 1, 'L');
        $pdf->SetDrawColor(75, 0, 130);
        $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
        $pdf->Ln(4);
        
        $pdf->SetFont('Arial', '', 10);
        $summary = $data['summary'];
        $pdf->Cell(60, 6, 'Total Equipment Types:', 0, 0);
        $pdf->Cell(30, 6, $summary['total_equipment_types'], 0, 1);
        $pdf->Cell(60, 6, 'Total Stock:', 0, 0);
        $pdf->Cell(30, 6, $summary['total_stock'], 0, 1);
        $pdf->Cell(60, 6, 'Usable Items:', 0, 0);
        $pdf->Cell(30, 6, $summary['total_usable'], 0, 1);
        $pdf->Cell(60, 6, 'Damaged Items:', 0, 0);
        $pdf->Cell(30, 6, $summary['total_damaged'], 0, 1);
        $pdf->Cell(60, 6, 'Sports Covered:', 0, 0);
        $pdf->Cell(30, 6, $summary['sports_covered'], 0, 1);
        $pdf->Cell(60, 6, 'Overall Condition:', 0, 0);
        $pdf->Cell(30, 6, $summary['overall_condition'] . '%', 0, 1);
        $pdf->Ln(8);
        
        // Equipment Table
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->Cell(0, 8, 'Equipment Inventory Details', 0, 1, 'L');
        $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
        $pdf->Ln(4);
        
        // Table Header
        $pdf->SetFont('Arial', 'B', 9);
        $pdf->SetFillColor(75, 0, 130);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->Cell(40, 8, 'Sport', 1, 0, 'C', true);
        $pdf->Cell(55, 8, 'Equipment Name', 1, 0, 'C', true);
        $pdf->Cell(25, 8, 'Stock', 1, 0, 'C', true);
        $pdf->Cell(25, 8, 'Usable', 1, 0, 'C', true);
        $pdf->Cell(25, 8, 'Damaged', 1, 0, 'C', true);
        $pdf->Cell(20, 8, 'Cond.%', 1, 1, 'C', true);
        
        // Table Rows
        $pdf->SetFont('Arial', '', 9);
        $pdf->SetTextColor(0, 0, 0);
        $fill = false;
        
        foreach ($data['equipment'] as $item) {
            // Alternate row colors
            $pdf->SetFillColor($fill ? 245 : 255, $fill ? 243 : 255, $fill ? 255 : 255);
            
            $pdf->Cell(40, 7, $this->truncate($item['sport_name'], 18), 1, 0, 'L', true);
            $pdf->Cell(55, 7, $this->truncate($item['equipment_name'], 25), 1, 0, 'L', true);
            $pdf->Cell(25, 7, $item['total_stock'], 1, 0, 'C', true);
            $pdf->Cell(25, 7, $item['usable'], 1, 0, 'C', true);
            $pdf->Cell(25, 7, $item['damaged'], 1, 0, 'C', true);
            
            // Color code condition
            $cond = $item['condition_percent'];
            if ($cond >= 80) {
                $pdf->SetTextColor(0, 150, 0);
            } elseif ($cond >= 50) {
                $pdf->SetTextColor(200, 130, 0);
            } else {
                $pdf->SetTextColor(200, 0, 0);
            }
            $pdf->Cell(20, 7, $cond . '%', 1, 1, 'C', true);
            $pdf->SetTextColor(0, 0, 0);
            
            $fill = !$fill;
        }
        
        // Footer
        $pdf->Ln(10);
        $pdf->SetFont('Arial', 'I', 8);
        $pdf->SetTextColor(120, 120, 120);
        $pdf->Cell(0, 5, '--- End of Report ---', 0, 1, 'C');
        $pdf->Cell(0, 5, 'UOC Sports E-Portal | Generated by Equipment Management System', 0, 1, 'C');
        
        // Output PDF
        $pdf->Output('D', 'Equipment_Inventory_Report_' . date('Y-m-d') . '.pdf');
        exit;
    }
    
    /**
     * Truncate string to max length
     */
    private function truncate($string, $length) {
        if (strlen($string) > $length) {
            return substr($string, 0, $length - 2) . '..';
        }
        return $string;
    }
}
