name: Deploy PHP Site

on:
  push:
    branches:
      - main  # change if your main branch is different

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload files to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps   # change to ftp if your host doesn't support ftps
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./    # path in your repo
          server-dir: ${{ secrets.FTP_REMOTE_PATH }}
          exclude: |
            **/.git*
            **/.github*
            **/README.md
